openapi: 3.0.0
info:
  title: hola
  version: 1.0.0
paths:
  /delete:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                type:
                  type: string
                format:
                  type: binary
      responses:
        '200':
          description: Successful response
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  description:
                    type: File Uploaded successfully
        '402':
          description: Payment Required
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
  /Address_postgres:
    get:
      summary: Finds Customers
      description: Multiple address values can be retrieved from employeeapp application
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
        '400':
          description: Invalid status value
