openapi: 3.0.0
info:
  title: Order Management API
  version: 1.0.0
paths:
  /orders:
    post:
      summary: Create a new order
      responses:
        '201':
          description: Order created successfully
        '400':
          description: Invalid input

    get:
      summary: Retrieve all orders
      responses:
        '200':
          description: A list of orders

  /orders/{id}:
    get:
      summary: Retrieve a specific order by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the order to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Order found
        '404':
          description: Order not found

    put:
      summary: Update a specific order by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the order to update
          schema:
            type: integer
      responses:
        '200':
          description: Order updated successfully
        '400':
          description: Invalid input
        '404':
          description: Order not found

    delete:
      summary: Delete a specific order by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the order to delete
          schema:
            type: integer
      responses:
        '204':
          description: Order deleted successfully
        '404':
          description: Order not found

  /categories:
    get:
      summary: Retrieve all categories
      responses:
        '200':
          description: A list of categories

    post:
      summary: Create a new category
      responses:
        '201':
          description: Category created successfully
        '400':
          description: Invalid input

  /categories/{id}:
    get:
      summary: Retrieve a specific category by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the category to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Category found
        '404':
          description: Category not found

    put:
      summary: Update a specific category by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the category to update
          schema:
            type: integer
      responses:
        '200':
          description: Category updated successfully
        '400':
          description: Invalid input
        '404':
          description: Category not found

    delete:
      summary: Delete a specific category by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the category to delete
          schema:
            type: integer
      responses:
        '204':
          description: Category deleted successfully
        '404':
          description: Category not found
